import { VolumeBar } from "../component/volume_bar.slint";
import { MySlider } from "./slider.slint";
    

export component Volume inherits Rectangle {
    in-out property <int> volume: 8;
    in property <int> volume-max: 56;
    in property <int> volume-step: 2;
   
    VerticalLayout {
        spacing: 10px;
        HorizontalLayout {
            spacing: 10px;

            VerticalLayout {
                padding: minus-touch-area.has-hover && !minus-touch-area.pressed ? 0px : 1px;
                alignment: center;
                minus-btn := Rectangle {
                    background: minus-touch-area.pressed ? #636363 :#000000;
                    height: minus-touch-area.has-hover && !minus-touch-area.pressed ? 8px : 6px;
                    width: minus-touch-area.has-hover && !minus-touch-area.pressed ? 24px : 22px;
                    border-radius: minus-touch-area.has-hover && !minus-touch-area.pressed ? 3px : 2px;
                    minus-touch-area := TouchArea {
                        clicked => {
                            root.volume = Math.max(0, root.volume - root.volume-step);
                        }
                    }
                }
            }

            HorizontalLayout {
                spacing: 2px;
                for index in 7: VolumeBar {
                    volume: root.volume;
                    start: 8 * index;
                    end: 8 * (index + 1);
                    height: 10px + 4px * (index + 1);
                    y: parent.height - self.height;
                    is-over: index > 4;

                }
            }

            VerticalLayout {
                padding: plus-touch-area.has-hover && !plus-touch-area.pressed ? 0px : 1px;
                alignment: center;
                Rectangle {
                    width: plus-touch-area.has-hover && !plus-touch-area.pressed ? 26px : 24px;
                    height: self.width;
                    plus-h-bar := Rectangle {
                        x: (parent.width * 0.5) - (self.width * 0.5);
                        background: plus-touch-area.pressed ? #636363 :#000000;
                        height: plus-touch-area.has-hover && !plus-touch-area.pressed ? 8px : 6px;
                        width: plus-touch-area.has-hover && !plus-touch-area.pressed ? 24px : 22px;
                        border-radius: plus-touch-area.has-hover && !plus-touch-area.pressed ? 3px : 2px;
                    }
                    plus-v-bar := Rectangle {
                        x: (parent.width * 0.5) - (self.width * 0.5);
                        y: (parent.height * 0.5) - (self.height * 0.5);
                        background: plus-touch-area.pressed ? #636363 :#000000;
                        width: plus-touch-area.has-hover && !plus-touch-area.pressed ? 8px : 6px;
                        height: plus-touch-area.has-hover && !plus-touch-area.pressed ? 24px : 22px;
                        border-radius: plus-touch-area.has-hover && !plus-touch-area.pressed ? 3px : 2px;
                    }

                    plus-touch-area := TouchArea {
                        clicked => {
                            root.volume = Math.min(root.volume-max, root.volume + root.volume-step);
                        }
                    }
                }
            }
            Text {
                font-size: 24px;
                font-weight: 600;
                text: Math.floor((root.volume / 42.0) * 100) + "%";
                vertical-alignment: center;
            }
        }
        MySlider {
            maximum: root.volume-max;
            value <=> root.volume;
            height: 12px;
        }
    }
}